### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by kianmeng** [comment]
@aforward Any updates on this?

**Comment by aforward** [comment]
Wow, I totally missed this PR sorry @kianmeng will take a look this week

**Comment by aforward** [comment]
I pulled in my updates for Elixir 1.13 and all the tests pass, going to merge shortly and then cut a new release

```
10:43 ~/sin/projects/doex (misc-doc-changes)$ mix test
===> Analyzing applications...
===> Compiling parse_trans
==> jason
Compiling 10 files (.ex)
Generated jason app
===> Analyzing applications...
===> Compiling certifi
===> Analyzing applications...
===> Compiling hackney
==> httpoison
Compiling 3 files (.ex)
Generated httpoison app
==> doex
Compiling 3 files (.ex)
Generated doex app
Excluding tags: [live: true]

......................................

Finished in 0.08 seconds (0.00s async, 0.08s sync)
13 doctests, 28 tests, 0 failures, 3 excluded

Randomized with seed 738242
```

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

There is also this PR, https://github.com/aforward/version_tasks/pull/1

**Pull request merged**
